# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            python-console
tagline:          An interpreter in a widget
url:              http://alextsui05.github.io
paginate:         1
baseurl:          /python-console
author:
  name:           Alex Tsui
  url:            https://twitter.com/alextsui
  email:          alextsui05@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://alextsui05.github.com/python-console
